import Link from 'next/link';
import { CATEGORY_LABELS, CATEGORY_ICONS, ArticleCategory } from '@/types';

const categories = Object.keys(CATEGORY_LABELS) as ArticleCategory[];

export default function HomePage() {
  return (
    <div>
      {/* Hero */}
      <div style={{
        padding: '40px 0 32px',
        borderBottom: '1px solid #1a3040',
        marginBottom: '32px',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '12px' }}>
          <div style={{
            fontSize: '3rem', filter: 'drop-shadow(0 0 12px rgba(240,192,64,0.4))'
          }}>☢</div>
          <div>
            <h1 style={{
              color: '#f0c040',
              fontSize: '2rem',
              fontFamily: 'Rajdhani, sans-serif',
              fontWeight: 700,
              letterSpacing: '0.15em',
              margin: 0,
              textShadow: '0 0 20px rgba(240,192,64,0.3)'
            }}>
              VAULT-76 WIKI
            </h1>
            <p style={{ color: '#8a8070', fontSize: '0.75rem', letterSpacing: '0.15em', margin: 0 }}>
              AI SEEDED · COMMUNITY VERIFIED · ALWAYS CURRENT
            </p>
          </div>
        </div>
        <p style={{ color: '#a0a898', fontSize: '0.9rem', maxWidth: '600px', lineHeight: 1.7, margin: 0 }}>
          The Fallout 76 knowledge base that updates with the game. Articles are generated by AI and flagged for review by the community — every fact you rely on has been human-verified.
        </p>

        <div style={{ display: 'flex', gap: '12px', marginTop: '20px', flexWrap: 'wrap' }}>
          <Link href="/wiki" className="pip-btn pip-btn-primary" style={{ textDecoration: 'none', display: 'inline-block' }}>
            Browse All Articles
          </Link>
          <Link href="/admin/seed" className="pip-btn" style={{ textDecoration: 'none', display: 'inline-block' }}>
            🤖 Generate Article
          </Link>
        </div>
      </div>

      {/* Category grid */}
      <div style={{ marginBottom: '32px' }}>
        <h2 style={{
          color: '#f0c040', fontSize: '0.75rem', letterSpacing: '0.2em',
          marginBottom: '16px', borderBottom: '1px solid #1a3040', paddingBottom: '8px'
        }}>
          BROWSE BY CATEGORY
        </h2>
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))',
          gap: '12px',
        }}>
          {categories.map(cat => (
            <Link key={cat} href={`/wiki?category=${cat}`}
              className="pip-card"
              style={{
                textDecoration: 'none',
                padding: '16px',
                display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '8px',
                borderRadius: '2px',
              }}
            >
              <span style={{ fontSize: '24px' }}>{CATEGORY_ICONS[cat]}</span>
              <span style={{
                color: '#e8e0c8', fontSize: '0.85rem',
                fontFamily: 'Rajdhani, sans-serif', fontWeight: 600,
                letterSpacing: '0.08em',
              }}>
                {CATEGORY_LABELS[cat]}
              </span>
            </Link>
          ))}
        </div>
      </div>

      {/* Status legend */}
      <div className="pip-card" style={{ padding: '16px', borderRadius: '2px' }}>
        <h2 style={{
          color: '#f0c040', fontSize: '0.7rem', letterSpacing: '0.2em',
          marginBottom: '12px', margin: '0 0 12px 0'
        }}>
          ARTICLE STATUS GUIDE
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {[
            { badge: 'ai_draft', label: 'AI DRAFT', desc: 'Generated by AI, not yet reviewed by the community.' },
            { badge: 'needs_review', label: 'NEEDS REVIEW', desc: 'Flagged by users — may contain errors. Awaiting mod approval.' },
            { badge: 'verified', label: 'VERIFIED', desc: 'Reviewed and approved by a moderator. Reliable.' },
          ].map(({ badge, label, desc }) => (
            <div key={badge} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
              <span className={`pip-badge-${badge === 'ai_draft' ? 'ai' : badge === 'needs_review' ? 'flagged' : 'verified'}`}
                style={{ flexShrink: 0, marginTop: '2px' }}>
                {label}
              </span>
              <span style={{ color: '#8a8070', fontSize: '0.8rem' }}>{desc}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
