import Link from 'next/link';
import { CATEGORY_LABELS, CATEGORY_ICONS, ArticleCategory } from '@/types';

const categories = Object.keys(CATEGORY_LABELS) as ArticleCategory[];

export default function HomePage() {
  return (
    <div>
      {/* Hero */}
      <div style={{ padding: '40px 0 32px', borderBottom: '1px solid #222330', marginBottom: '32px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '14px' }}>
          <div style={{ fontSize: '3rem', filter: 'drop-shadow(0 0 14px rgba(217,175,47,0.5))', color: '#D9AF2F' }}>☢</div>
          <div>
            <h1 style={{
              color: '#D9AF2F',
              fontSize: '2.2rem',
              fontFamily: 'Rajdhani, sans-serif',
              fontWeight: 700,
              letterSpacing: '0.15em',
              margin: 0,
              textShadow: '0 0 24px rgba(217,175,47,0.35)',
            }}>
              VAULT-76 WIKI
            </h1>
            <p style={{ color: '#4a4840', fontSize: '0.7rem', letterSpacing: '0.2em', margin: 0 }}>
              AI SEEDED · COMMUNITY VERIFIED · ALWAYS CURRENT
            </p>
          </div>
        </div>
        <p style={{ color: '#7a7268', fontSize: '0.9rem', maxWidth: '580px', lineHeight: 1.7, margin: '0 0 20px' }}>
          The Fallout 76 knowledge base that updates with the game. Articles are generated by AI and verified by the community — every fact you rely on has been human-checked.
        </p>
        <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap' }}>
          <Link href="/wiki" className="pip-btn pip-btn-primary" style={{ textDecoration: 'none', display: 'inline-block' }}>
            Browse All Articles
          </Link>
          <Link href="/admin/seed" className="pip-btn" style={{ textDecoration: 'none', display: 'inline-block' }}>
            🤖 Generate Article
          </Link>
        </div>
      </div>

      {/* Category grid */}
      <div style={{ marginBottom: '32px' }}>
        <h2 style={{
          color: '#4a4840', fontSize: '0.7rem', letterSpacing: '0.2em',
          marginBottom: '14px', borderBottom: '1px solid #222330', paddingBottom: '8px'
        }}>
          BROWSE BY CATEGORY
        </h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(155px, 1fr))', gap: '10px' }}>
          {categories.map(cat => (
            <Link key={cat} href={`/wiki?category=${cat}`}
              className="pip-card"
              style={{ textDecoration: 'none', padding: '16px', display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '8px', borderRadius: '2px' }}
            >
              <span style={{ fontSize: '22px' }}>{CATEGORY_ICONS[cat]}</span>
              <span style={{ color: '#E8DFC8', fontSize: '0.85rem', fontFamily: 'Rajdhani, sans-serif', fontWeight: 600, letterSpacing: '0.06em' }}>
                {CATEGORY_LABELS[cat]}
              </span>
            </Link>
          ))}
        </div>
      </div>

      {/* Status legend */}
      <div className="pip-card" style={{ padding: '18px', borderRadius: '2px' }}>
        <h2 style={{ color: '#4a4840', fontSize: '0.7rem', letterSpacing: '0.2em', margin: '0 0 14px' }}>
          ARTICLE STATUS GUIDE
        </h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
          {[
            { cls: 'pip-badge-ai', label: 'AI DRAFT', desc: 'Generated by AI, not yet reviewed by the community.' },
            { cls: 'pip-badge-flagged', label: 'NEEDS REVIEW', desc: 'Flagged by users — may contain errors. Awaiting mod approval.' },
            { cls: 'pip-badge-verified', label: 'VERIFIED', desc: 'Reviewed and approved by a moderator. Reliable.' },
          ].map(({ cls, label, desc }) => (
            <div key={label} style={{ display: 'flex', alignItems: 'flex-start', gap: '10px' }}>
              <span className={cls} style={{ flexShrink: 0, marginTop: '2px' }}>{label}</span>
              <span style={{ color: '#7a7268', fontSize: '0.8rem' }}>{desc}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
