'use client';
import { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { Article, ArticleStatus, CATEGORY_LABELS, CATEGORY_ICONS, ArticleCategory } from '@/types';
import { Flag, ChevronLeft } from 'lucide-react';

function StatusBadge({ status }: { status: ArticleStatus }) {
  if (status === 'verified') return <span className="pip-badge-verified">✓ VERIFIED</span>;
  if (status === 'needs_review') return <span className="pip-badge-flagged">⚑ NEEDS REVIEW</span>;
  return <span className="pip-badge-ai">🤖 AI DRAFT</span>;
}

export default function ArticlePage() {
  const { slug } = useParams();
  const [article, setArticle] = useState<Article | null>(null);
  const [loading, setLoading] = useState(true);
  const [flagging, setFlagging] = useState(false);
  const [flagReason, setFlagReason] = useState('');
  const [flagDetail, setFlagDetail] = useState('');
  const [flagged, setFlagged] = useState(false);
  const [showFlagForm, setShowFlagForm] = useState(false);

  useEffect(() => {
    fetch(`/api/articles/${slug}`)
      .then(r => r.json())
      .then(data => { setArticle(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, [slug]);

  async function submitFlag() {
    if (!flagReason || !article) return;
    setFlagging(true);
    await fetch(`/api/flag`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ article_id: article.id, reason: flagReason, detail: flagDetail }),
    });
    setFlagged(true);
    setFlagging(false);
    setShowFlagForm(false);
  }

  if (loading) return <div style={{ color: '#8a8070', padding: '60px', textAlign: 'center' }} className="pip-pulse">LOADING...</div>;
  if (!article) return <div style={{ color: '#c04040', padding: '60px', textAlign: 'center' }}>Article not found.</div>;

  return (
    <div>
      {/* Breadcrumb */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px', fontSize: '0.75rem', color: '#8a8070' }}>
        <Link href="/wiki" style={{ color: '#8a8070', textDecoration: 'none', display: 'flex', alignItems: 'center', gap: '4px' }}>
          <ChevronLeft size={14} /> Browse
        </Link>
        <span>/</span>
        <Link href={`/wiki?category=${article.category}`} style={{ color: '#8a8070', textDecoration: 'none' }}>
          {CATEGORY_ICONS[article.category as ArticleCategory]} {CATEGORY_LABELS[article.category as ArticleCategory]}
        </Link>
        <span>/</span>
        <span style={{ color: '#e8e0c8' }}>{article.title}</span>
      </div>

      {/* Article header */}
      <div style={{ borderBottom: '1px solid #1a3040', paddingBottom: '16px', marginBottom: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '12px', flexWrap: 'wrap' }}>
          <div>
            <h1 style={{
              color: '#f0c040', fontSize: '1.8rem',
              fontFamily: 'Rajdhani, sans-serif', fontWeight: 700,
              letterSpacing: '0.08em', margin: '0 0 8px',
              textShadow: '0 0 16px rgba(240,192,64,0.2)'
            }}>{article.title}</h1>
            <div style={{ display: 'flex', gap: '8px', alignItems: 'center', flexWrap: 'wrap' }}>
              <StatusBadge status={article.status} />
              <span className="category-tag">{CATEGORY_ICONS[article.category as ArticleCategory]} {CATEGORY_LABELS[article.category as ArticleCategory]}</span>
              <span style={{ color: '#4a6070', fontSize: '0.7rem' }}>{article.view_count} views</span>
              <span style={{ color: '#4a6070', fontSize: '0.7rem' }}>Updated {new Date(article.updated_at).toLocaleDateString()}</span>
            </div>
          </div>
          <button
            className="pip-btn"
            onClick={() => setShowFlagForm(!showFlagForm)}
            style={{ display: 'flex', alignItems: 'center', gap: '6px', flexShrink: 0 }}
          >
            <Flag size={13} /> FLAG ERROR
          </button>
        </div>

        {/* AI disclaimer */}
        {article.ai_generated && article.status !== 'verified' && (
          <div style={{
            marginTop: '12px', padding: '8px 12px',
            background: 'rgba(26, 58, 92, 0.3)',
            border: '1px solid #2a4a6a',
            fontSize: '0.75rem', color: '#7ab8e8',
          }}>
            ⚠ This article was generated by AI and has not been fully verified. Information may be incomplete or inaccurate. Flag any errors you find.
          </div>
        )}
      </div>

      {/* Flag form */}
      {showFlagForm && !flagged && (
        <div className="pip-card" style={{ padding: '16px', marginBottom: '20px', borderRadius: '2px' }}>
          <h3 style={{ color: '#f0c040', fontSize: '0.8rem', letterSpacing: '0.12em', margin: '0 0 12px' }}>REPORT AN ERROR</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <select className="pip-input" value={flagReason} onChange={e => setFlagReason(e.target.value)}>
              <option value="">Select reason...</option>
              <option value="incorrect_info">Incorrect information</option>
              <option value="outdated">Outdated (game was patched)</option>
              <option value="missing_info">Missing important info</option>
              <option value="wrong_values">Wrong values/numbers</option>
              <option value="other">Other</option>
            </select>
            <textarea
              className="pip-input"
              placeholder="Optional: describe the issue..."
              value={flagDetail}
              onChange={e => setFlagDetail(e.target.value)}
              rows={3}
              style={{ resize: 'vertical' }}
            />
            <div style={{ display: 'flex', gap: '8px' }}>
              <button className="pip-btn pip-btn-primary" onClick={submitFlag} disabled={!flagReason || flagging}>
                {flagging ? 'SUBMITTING...' : 'SUBMIT FLAG'}
              </button>
              <button className="pip-btn" onClick={() => setShowFlagForm(false)}>CANCEL</button>
            </div>
          </div>
        </div>
      )}
      {flagged && (
        <div style={{ padding: '12px', background: 'rgba(74,154,96,0.15)', border: '1px solid #4a9a60', color: '#4a9a60', fontSize: '0.8rem', marginBottom: '20px' }}>
          ✓ Flag submitted — a moderator will review this article.
        </div>
      )}

      {/* Article content */}
      <div className="article-content" dangerouslySetInnerHTML={{ __html: article.content }} />
    </div>
  );
}
